name: Linux Release Build
on:
  push: 
    tags:
    - "*"
jobs:
  build-linux64:
    name: Build Linux64 package
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4 
      with:
        python-version: ${{matrix.python-version}}
    - name: Checking python distrubution structure ...
      run: |
        which python
        CIPHEY_CORE_PYTHON=$(dirname $(dirname $(which python)))
        echo "CIPHEY_CORE_PYTHON: $CIPHEY_CORE_PYTHON"
        ls -lR $CIPHEY_CORE_PYTHON/*/*
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libboost-dev cmake build-essential swig
    - name: Install required python build tools
      run: |
        python -m pip install poetry auditwheel setuptools
    - name: Do build
      run: |
        mkdir build && cd build
        export CIPHEY_CORE_PYTHON=$(dirname $(dirname $(which python)))
        echo "CIPHEY_CORE_PYTHON: $CIPHEY_CORE_PYTHON"
        cmake .. -DCIPHEY_CORE_TEST=OFF -DCMAKE_BUILD_TYPE=Release -DCIPHEY_CORE_PYTHON=$CIPHEY_CORE_PYTHON
        # cmake .. -DCIPHEY_CORE_TEST=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build .
    - name: Create python package
      run: |
        cd build
        python -V
        python -m poetry build
        python -m auditwheel show dist/*.whl
        # Failed now on ubuntu 20.04, skip?
        # cannot repair "dist/cipheycore-0.3.2-cp310-cp310-manylinux_2_31_x86_64.whl" to "manylinux_2_5_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
        # python -m auditwheel repair dist/*.whl
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_short_version }}
        file: |-
          build/dist/*.whl
        tags: true
        draft: false
        overwrite: true

